# Generated by Django 6.0.2 on 2026-04-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_squadsubmission_formation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadsubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved by Coordinator'), ('rejected', 'Rejected — Needs Changes'), ('locked', 'Locked by Secretary General')], default='draft', max_length=20),
        ),
    ]
