# Generated by Django 6.0.2 on 2026-03-19 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0019_countydelegationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discipline',
            field=models.ForeignKey(blank=True, help_text='Discipline this team is registered for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.countydiscipline'),
        ),
    ]
