# Generated by Django 6.0.2 on 2026-04-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_team_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'sport_type')},
        ),
    ]
