# Generated by Django 6.0.2 on 2026-04-04 09:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_activitylog_changes_json_alter_activitylog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('TEAM_CREATE', 'Team Created'), ('TEAM_UPDATE', 'Team Updated'), ('TEAM_DELETE', 'Team Deleted'), ('TEAM_APPROVE', 'Team Approved'), ('TEAM_REJECT', 'Team Rejected'), ('TEAM_SUSPEND', 'Team Suspended'), ('PLAYER_CREATE', 'Player Created'), ('PLAYER_UPDATE', 'Player Updated'), ('PLAYER_DELETE', 'Player Deleted'), ('PLAYER_TRANSFER', 'Player Transfer'), ('MATCH_CREATE', 'Match Created'), ('MATCH_UPDATE', 'Match Updated'), ('MATCH_DELETE', 'Match Deleted'), ('MATCH_RESCHEDULE', 'Match Rescheduled'), ('MATCH_REPORT', 'Match Report Submitted'), ('MATCH_REPORT_APPROVE', 'Match Report Approved'), ('RESULT_OVERRIDE', 'Result Override'), ('STANDINGS_OVERRIDE', 'Standings Override'), ('SG_OVERRIDE_ACK', 'SG Override Acknowledged'), ('SG_OVERRIDE_REJECT', 'SG Override Rejected'), ('FIXTURE_GENERATE', 'Fixtures Generated'), ('FIXTURE_REGENERATE', 'Fixtures Regenerated'), ('ZONE_ASSIGN', 'Zone Assigned'), ('ZONE_UPDATE', 'Zone Updated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_VERIFIED', 'Payment Verified'), ('SUSPENSION_CREATE', 'Suspension Created'), ('SUSPENSION_LIFT', 'Suspension Lifted'), ('MATCHDAY_SQUAD_SUBMIT', 'Matchday Squad Submitted'), ('SQUAD_APPROVE', 'Squad Approved'), ('SQUAD_REJECT', 'Squad Rejected'), ('REFEREE_REGISTER', 'Referee Registered'), ('REFEREE_APPROVE', 'Referee Approved'), ('REFEREE_ACTION', 'Referee Action'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('USER_ROLE_CHANGE', 'User Role Changed'), ('CONFIG_CHANGE', 'Configuration Changed'), ('REGISTRATION_TOGGLE', 'Registration Window Toggled'), ('ADMIN_ACTION', 'Admin Action'), ('PAYMENT_ACTION', 'Payment Action'), ('OTHER', 'Other Action')], max_length=50),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUT', 'Outgoing'), ('IN', 'Incoming')], default='OUT', max_length=3)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('draft', 'Draft')], default='sent', max_length=10)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_emails', models.TextField(help_text='Comma-separated recipient emails')),
                ('cc_emails', models.TextField(blank=True, default='')),
                ('bcc_emails', models.TextField(blank=True, default='')),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('error_message', models.TextField(blank=True, help_text='Error details if send failed')),
                ('message_id', models.CharField(blank=True, db_index=True, help_text='RFC 2822 Message-ID for deduplication', max_length=255)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='admin_dashb_sent_at_fcf085_idx'), models.Index(fields=['status', '-sent_at'], name='admin_dashb_status_f62f4a_idx')],
            },
        ),
    ]
