# Generated by Django 6.0.2 on 2026-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_add_basketball_handball_gender_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='live_extra_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Injury/stoppage time added to current period'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='live_half',
            field=models.PositiveIntegerField(blank=True, help_text='Current period: 1=1st half, 2=2nd half, 3=ET1, 4=ET2, 99=penalties', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='live_paused',
            field=models.BooleanField(default=False, help_text='Is the match clock currently stopped?'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='live_paused_minute',
            field=models.PositiveIntegerField(blank=True, help_text='Minute at which clock was paused', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='live_started_at',
            field=models.DateTimeField(blank=True, help_text='When the match actually kicked off', null=True),
        ),
    ]
