# Generated by Django 6.0.2 on 2026-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_fixture_live_extra_minutes_fixture_live_half_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='knockout_round',
            field=models.CharField(blank=True, choices=[('quarterfinal', 'Quarter-final'), ('semifinal', 'Semi-final'), ('third_place', '3rd Place Play-off'), ('final', 'Final')], default='', help_text='Applicable knockout round (R16, QF, SF, Final)', max_length=20),
        ),
    ]
