# Generated by Django 6.0.2 on 2026-04-17 10:11

from django.db import migrations


def deactivate_meru_venues(apps, schema_editor):
    Venue = apps.get_model('competitions', 'Venue')
    Venue.objects.filter(county__iexact='Meru').update(is_active=False)


def reactivate_meru_venues(apps, schema_editor):
    Venue = apps.get_model('competitions', 'Venue')
    Venue.objects.filter(county__iexact='Meru').update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_fixture_knockout_round'),
    ]

    operations = [
        migrations.RunPython(deactivate_meru_venues, reactivate_meru_venues),
    ]
