# Generated by Django 6.0.2 on 2026-04-17

from datetime import date, time
from django.db import migrations
from django.utils import timezone


def create_qf_fixtures(apps, schema_editor):
    """Create 3 quarterfinal knockout fixtures at Ndururumo 3."""
    Fixture = apps.get_model('competitions', 'Fixture')
    Venue = apps.get_model('competitions', 'Venue')
    Competition = apps.get_model('competitions', 'Competition')
    Team = apps.get_model('teams', 'Team')
    County = apps.get_model('teams', 'County')

    # Find an active/group_stage/knockout competition (men's football)
    comp = Competition.objects.filter(
        status__in=['group_stage', 'knockout', 'active']
    ).order_by('-season').first()
    if not comp:
        return

    # Venue: Ndururumo 3 (Meru)
    venue = Venue.objects.filter(name__icontains='Ndururumo 3').first()
    if not venue:
        venue = Venue.objects.filter(name__icontains='Ndururumo').first()

    def find_team(county_name):
        """Find a men's football team by county name."""
        county = County.objects.filter(name__icontains=county_name).first()
        if county:
            team = Team.objects.filter(county=county, sport_type='football_men').first()
            if not team:
                team = Team.objects.filter(county=county).first()
            return team
        # Fallback: search by team name
        return Team.objects.filter(name__icontains=county_name).first()

    busia = find_team('Busia')
    nyandarua = find_team('Nyandarua')
    laikipia = find_team('Laikipia')
    wajir = find_team('Wajir')
    mandera = find_team('Mandera')
    makueni = find_team('Makueni')

    today = date.today()

    # QF 1: Busia 2-1 Nyandarua (FT)
    if busia and nyandarua:
        fx = Fixture.objects.create(
            competition=comp,
            home_team=busia,
            away_team=nyandarua,
            venue=venue,
            match_date=today,
            kickoff_time=time(15, 0),
            status='completed',
            is_knockout=True,
            knockout_round='quarterfinal',
            bracket_position=1,
            home_score=2,
            away_score=1,
            winner=busia,
        )

    # QF 2: Laikipia 0-0 Wajir (LIVE, minute 3)
    if laikipia and wajir:
        fx = Fixture.objects.create(
            competition=comp,
            home_team=laikipia,
            away_team=wajir,
            venue=venue,
            match_date=today,
            kickoff_time=time(15, 0),
            status='live',
            is_knockout=True,
            knockout_round='quarterfinal',
            bracket_position=2,
            home_score=0,
            away_score=0,
            live_half=1,
            live_started_at=timezone.now(),
        )

    # QF 3: Mandera 0-1 Makueni (FT)
    if mandera and makueni:
        fx = Fixture.objects.create(
            competition=comp,
            home_team=mandera,
            away_team=makueni,
            venue=venue,
            match_date=today,
            kickoff_time=time(15, 0),
            status='completed',
            is_knockout=True,
            knockout_round='quarterfinal',
            bracket_position=3,
            home_score=0,
            away_score=1,
            winner=makueni,
        )


def remove_qf_fixtures(apps, schema_editor):
    Fixture = apps.get_model('competitions', 'Fixture')
    Fixture.objects.filter(
        is_knockout=True,
        knockout_round='quarterfinal',
        bracket_position__in=[1, 2, 3],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_deactivate_meru_venues'),
        ('teams', '0020_team_discipline'),
    ]

    operations = [
        migrations.RunPython(create_qf_fixtures, remove_qf_fixtures),
    ]
