# Generated by Django 6.0.2 on 2026-04-17 10:39

from django.db import migrations
from django.db.models import Q


def delete_tbd_fixtures(apps, schema_editor):
    Fixture = apps.get_model('competitions', 'Fixture')
    deleted = Fixture.objects.filter(
        Q(home_team__name__icontains='TBD') | Q(away_team__name__icontains='TBD')
    ).delete()
    print(f'Deleted {deleted[0]} TBD fixtures')


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_create_qf_fixtures'),
    ]

    operations = [
        migrations.RunPython(delete_tbd_fixtures, migrations.RunPython.noop),
    ]
